"""add click_events table

Revision ID: 11e8b3c50e56
Revises: 09e5e25acf67
Create Date: 2026-04-22 10:10:08.908391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e8b3c50e56'
down_revision: Union[str, Sequence[str], None] = '09e5e25acf67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('click_events', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('click_events', 'link_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('click_events_link_id_fkey'), 'click_events', type_='foreignkey')
    op.create_foreign_key(None, 'click_events', 'links', ['link_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'click_events', type_='foreignkey')
    op.create_foreign_key(op.f('click_events_link_id_fkey'), 'click_events', 'links', ['link_id'], ['id'], ondelete='CASCADE')
    op.alter_column('click_events', 'link_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('click_events', 'created_at')
    # ### end Alembic commands ###
