"""add expires_at to links

Revision ID: 2b03540b0179
Revises: 11e8b3c50e56
Create Date: 2026-04-22 15:47:52.825756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b03540b0179'
down_revision: Union[str, Sequence[str], None] = '11e8b3c50e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'expires_at')
    # ### end Alembic commands ###
